### ISSUE TITLE
Bus error from diagnose/repair

### ISSUE THREAD

**Issue by dmtucker** [clearlinux/swupd-client#1168]
**Describe the bug**
I cannot successfully run `swupd diagnose` or `swupd repair` (even after `swupd clean --all`) because I get a Bus error 37% through "Checking for corrupt files".

**To Reproduce**
```
[11] dtux@nucleus:~ $ sudo swupd repair --debug
Password: 
2019-10-24 12:22:41 (src/verify.c:899)            Diagnosing version 31380
2019-10-24 12:22:41 (src/verify.c:1027)           Downloading missing manifests...
2019-10-24 12:22:41 (src/verify.c:259)            
2019-10-24 12:22:41 (src/verify.c:219)            Checking for corrupt files
2019-10-24 12:22:41 (src/lib/progress.c:117)      	...0%
2019-10-24 12:22:41 (src/lib/progress.c:117)      	...1%
2019-10-24 12:22:41 (src/lib/progress.c:117)      	...2%
2019-10-24 12:22:41 (src/lib/progress.c:117)      	...3%
2019-10-24 12:22:41 (src/lib/progress.c:117)      	...4%
2019-10-24 12:22:41 (src/lib/progress.c:117)      	...5%
2019-10-24 12:22:42 (src/lib/progress.c:117)      	...6%
2019-10-24 12:22:42 (src/lib/progress.c:117)      	...7%
2019-10-24 12:22:42 (src/lib/progress.c:117)      	...8%
2019-10-24 12:22:42 (src/lib/progress.c:117)      	...9%
2019-10-24 12:22:42 (src/lib/progress.c:117)      	...10%
2019-10-24 12:22:42 (src/lib/progress.c:117)      	...11%
2019-10-24 12:22:42 (src/lib/progress.c:117)      	...12%
2019-10-24 12:22:42 (src/lib/progress.c:117)      	...13%
2019-10-24 12:22:42 (src/lib/progress.c:117)      	...14%
2019-10-24 12:22:42 (src/lib/progress.c:117)      	...15%
2019-10-24 12:22:42 (src/lib/progress.c:117)      	...16%
2019-10-24 12:22:42 (src/lib/progress.c:117)      	...17%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...18%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...19%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...20%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...21%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...22%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...23%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...24%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...25%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...26%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...27%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...28%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...29%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...30%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...31%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...32%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...33%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...34%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...35%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...36%
2019-10-24 12:22:43 (src/lib/progress.c:117)      	...37%
Bus error
2019-10-24T12:22:43-0700 exit 135
```

**Expected behavior**
(I've never tried to run it before, but I assume it doesn't throw bus errors usually 😋.)

For what it's worth, I started trying to run it because I appear to have `python3-basic` installed, but no `pip`:
```
[13] dtux@nucleus:~ $ python3 -Im ensurepip --upgrade --default-pip  # originally run by pipx
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/usr/lib/python3.7/ensurepip/__init__.py", line 204, in _main
    default_pip=args.default_pip,
  File "/usr/lib/python3.7/ensurepip/__init__.py", line 99, in _bootstrap
    "_bundled/{}".format(wheel_name),
  File "/usr/lib/python3.7/pkgutil.py", line 637, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.7/ensurepip/_bundled/pip-19.2.3-py2.py3-none-any.whl'
```

**Environment (please complete the following information):**
 - Clear Linux OS Version: 31380, swupd-client 3.22.3
 - Platform: I'm running on a NUC 7i7BNH (Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz, 32GB RAM -- more info available if needed)

**Comment by dmtucker** [comment]
Reproduces on 31440
```
[3] dtux@nucleus:~ $ sudo swupd clean --all
158 files removed
2019-10-29T16:37:37-0700 exit 0
[4] dtux@nucleus:~ $ sudo swupd diagnose
Diagnosing version 31440
Downloading missing manifests...
 [-]
Checking for missing files
 -> Missing file: /usr/share/dpdk/mk/exec-env/linux/rte.app.mk
 -> Missing file: /usr/share/dpdk/mk/exec-env/linux/rte.vars.mk
 [100%]


Checking for corrupt files
Bus error
2019-10-29T16:37:50-0700 exit 135
[5] dtux@nucleus:~ $ sudo swupd repair
Diagnosing version 31440
Downloading missing manifests...

Checking for corrupt files
Bus error
2019-10-29T16:38:28-0700 exit 135
```

**Comment by dmtucker** [comment]
I was able to run `repair` successfully on 31870!

**Comment by dmtucker** [comment]
I haven't been able to reproduce since with `diagnose` or `repair`. Closing...
